version: '3.8'

services:
  db:
    image: postgres:latest
    env_file:
      - .env.docker
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  web:
    build:
      context: .
    command: sh -c "sh init_db.sh && uvicorn main:app --host 0.0.0.0 --port 8000"
    volumes:
      - ./app:/app
      - ./mydb.sql:/data/mydb.sql
    env_file:
      - .env.docker
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

volumes:
  postgres_data:
